### ISSUE TITLE
duvida pstk

### ISSUE THREAD

**Issue by joaotadiello** [leonardonm15/BetTech#3]
salve pessoal, tava dando uma olhada no projeto de voces, queria tirar uma duvida é possivel burlar o sistema de saque? usando o pstk de um conta nao verificada, para trocar o cpf na conta verificada?

**Comment by leonardonm15** [comment]
não pensamos sobre esse tipo de possibilidade, até pq o projeto era focado no monitoramento de padrões nas diversas roletas, mas é algo a se pensar, talvez eu faça alguns testes com o Enzo !

obs: perdão a demora
